# --- !Ups

CREATE TABLE user (
    name VARCHAR(32) NOT NULL PRIMARY KEY,
    password VARCHAR(32) NOT NULL
);

INSERT INTO user VALUES ('葛海明', '123456'), ('刘吉龙', '123456'), ('卫国瑞', '123456'), ('葛晓俊', '123456');

CREATE SEQUENCE bill_id_seq START WITH 10000;
CREATE TABLE bill (
    id BIGINT PRIMARY KEY,
    name VARCHAR(4096) NOT NULL,
    pay DOUBLE NOT NULL,
    payer VARCHAR(32) NOT NULL,
    date DATE NOT NULL,
    deleted BOOLEAN NOT NULL,
    FOREIGN KEY (payer) REFERENCES user(name) ON DELETE RESTRICT
);

CREATE TABLE SETTLEMENT (
	id INT PRIMARY KEY AUTO_INCREMENT,
	bill BIGINT NOT NULL,
	FOREIGN KEY (bill) REFERENCES bill(id) ON DELETE RESTRICT
);


# --- !Downs
 
DROP TABLE IF EXISTS user;
DROP SEQUENCE IF EXISTS bill_id_seq;
DROP TABLE IF EXISTS bill;
